### ISSUE TITLE
Missing emoji, Brown Heart

### ISSUE THREAD

**Issue by Michael-Loia** [Magisk-Modules-Repo/systemless-unicode9-ios10-Emoji#27]
This is missing the brown heart emoji.

I noticed it after a friend of mine had a box instead of the brown heart emoji I put on there name

Thanks - Michael Loia

**Comment by ChiefMikeK** [comment]
🚩 New in iOS 13.2 this module is updated only to iOS 12.1 ???
[🤎 U+1F90E Brown Heart Emoji@emojipedia](https://emojipedia.org/brown-heart/)
